apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
      - name: prometheus-monitoring
        image: prom/prometheus
        resources:
          requests:
            memory: "256Mi"  # Lower requested memory
            cpu: "500m"      # Lower requested CPU (500m = 0.5 CPU)
          limits:
            memory: "0.5Gi"
            cpu: "1"
        ports:
        - containerPort: 9090
        volumeMounts:
          - name: prometheus-conf-volume
            mountPath: /etc/prometheus/prometheus.yml
            subPath: prometheus.yml
      
      volumes:
        - name: prometheus-conf-volume
          configMap:
            name: prometheus-config 
          

